spring:
  application:
    name: springboot-ssm
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: defaultDataSource
      url: jdbc:mysql://localhost:3306/fmmall?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: rjyhshyk0208

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: cn.azh.fmmall.entity

